### PR TITLE
Add "Finalize Tasks: Scan for restore" option

### PR DESCRIPTION
**Pull request by timsutton**
This makes it possible to skip the ASR restore phase, as I suggested in #144. This works, although some things aren't yet done:

- [x] CLI option
- [x] Advanced Window is messed up - I have no idea what I'm doing with UI layouts yet
- [x] The `SkipAsrImagescan` template key gets written to the plist in the .adtmpl baked into the image, but if I just do a save within AutoDMG this property isn't saved - in testing this I noticed that `VolumeSize` doesn't seem to either, although `VolumeName` does

### CODE REVIEW

**Comment by timsutton** [comment]
I think this is ready for review and testing. Would you like me to first squash these down to one commit?

**Comment by timsutton** [comment]
Flipped the boolean logic as discussed in Slack. Force pushed this because I rolled back to an earlier xib to redo it. Will test this more thoroughly tomorrow, though.

**Comment by timsutton** [comment]
Seems good. I can load a template with either 1) no `FinalizeAsrImagescan` key set, or 2) that key set to True, and the default of scanning for restore is set.

All that's left is the CLI option. Do you like the option `--skip-asr-imagescan`, or should we switch to something that perhaps matches the naming better, like `--no-finalize-asr-imagescan`?

**Comment by MagerValp** [comment]
Less typing is better, so `--skip-asr-imagescan` sounds good to me, there's no reason it has to match the template variable.

**Comment by timsutton** [comment]
:+1:

**Comment by timsutton** [comment]
Done. If you haven't checked this out yet, and/or would prefer a single commit, let me know!

**Pull request merged**
